### PR TITLE
Add `ignore_certificate_hosts` option

### LINKED ISSUE #109: Use self signed certificates
Use of self signed or invalid certificates are common in dev environmnts. But I cannot find anything in the docs about how to tell slumber to ignore certificate errors, and when I tried to contact a server with a root cert not in the trusted chain I get:
```
invalid peer certificate: UnknownIssuer
```
It would be nice if this could be documented if it is possible already, or implemented if not currently possible.

### PR DESCRIPTION
**Pull request by LucasPickering**
This allows you to ignore TLS cert errors on certain domains. Closes #109

### CODE REVIEW

**Comment by snaggen** [comment]
I just tested this, and the certificat error still just say 
error trying to connect: invalid peer certificate: Unknown Issuer. 

I would add to that error message: 
'If this is expected, add ignore_certificate_hosts: ["<hostname>"] to allow this. '
And if not to hard, replace <hostname> with the real hostname

**Comment by snaggen** [comment]
I cannot get this to work either.
```
  rest_call:
    method: GET
    ignore_certificate_hosts: ["www.host.com", "1.2.3.4"]
    authorization: !basic
      username: "{{username}}"
      password: "{{password}}"
    url: "{{base_url}}/rest/call/path"
```

I have a call like this, and I still see the Unknown Issuer error
As you see, I have added both the dns name and the IP adress

**Comment by LucasPickering** [comment]
@snaggen The field is `authentication`, not `authorization`

**Comment by LucasPickering** [comment]
@snaggen This field needs to be set in the config file, not the collection file: https://slumber.lucaspickering.me/book/troubleshooting/tls.html

And the error message is hard to change because it's being forwarded from reqwest, which doesn't provide any metadata on the error to tell you what it is. We would have to check against the error message directly but that's fragile because it could change at any time.

**Pull request merged**
