### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by deining**
This PR fixes various typos I spotted in the project.

### CODE REVIEW

**Comment by deining** [comment]
All checks are passing now :smile:.

**Review by ttytm — COMMENTED** [review]
Since the format linter was only triggering for two of the longer doc comments with fixed typos, I think those should be the only ones for which formatting should have been fixed. Making other formatting changes seems out of scope for the PR.

**Comment by deining** [comment]
> Since the format linter was only triggering for two of the longer doc comments with fixed typos, I think those should be the only ones for which formatting should have been fixed. Making other formatting changes seems out of scope for the PR.

You are right. Just reverted all changes from my second commit not related to typo fixing.

**Review by ttytm — COMMENTED** [review]
I don't have access rights for submitting a formal approving review, but it's looking good now. Good job :+1:.

**Comment by LucasPickering** [comment]
ty!

**Pull request merged**
