### PR TITLE
Add shortcuts for defining authentication in a recipe

### LINKED ISSUE #110: Add more convenient way to set authorization
I don't know if there is any support for Basic Auth, couldn't find it in the docs. If not, it would be nice to have. Currently I just set the header Authorization: Basic ... , but I think it would be nice to be able to set the username and password instead.

### PR DESCRIPTION
**Pull request by LucasPickering**
For now only Basic and Bearer auth are supported, but more can be added later. Closes #110

### CODE REVIEW

**Comment by snaggen** [comment]
I couldn't get this to work
I have 
```
  rest_call:
    method: GET
    ignore_certificate_hosts: ["www.host.com", "1.2.3.4"]
    authorization: !basic
      username: "{{username}}"
      password: "{{password}}"
    url: "{{base_url}}/rest/call/path"
```
But I still get a 401 back

**Comment by snaggen** [comment]
Looking at tcpdump I cannot see an Authorization header

**Comment by LucasPickering** [comment]
@snaggen This feature isn't released yet, just merged to master

**Comment by snaggen** [comment]
Well, I was compiling and testing master

**Comment by LucasPickering** [comment]
@snaggen The field is `authentication`, not `authorization`

**Comment by snaggen** [comment]
Ahh... I was just taking the snippet from the linked issue.... 
Now I get the header, but it is wrong:
```authorization: YABpdXjiKpsrlcjp2OE4zQnlMhMWno```
should be 
```authorization: Basic YABpdXjiKpsrlcjp2OE4zQnlMhMWno```

**Comment by LucasPickering** [comment]
Oops! Thank you for testing, I did this in a hurry and got sloppy. I'm in the process of writing tests for this because I forgot to in the original MR, I'll try to get it fixed today.

**Pull request merged**
